from sqlalchemy.orm import sessionmaker, declarative_base
from sqlalchemy import create_engine
from dotenv import load_dotenv
load_dotenv()
import os
DATABASE_NAME= os.getenv('DATABASE_NAME')
DATABASE_PASSWORD= os.getenv('DATABASE_PASSWORD')
DATABASE_USER=os.getenv('DATABASE_USER')
DATABASE_HOST=os.getenv('DATABASE_HOST')
DATABASE_PORT=os.getenv('DATABASE_PORT')

DATABASE_URL=f"postgresql+psycopg2://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}"

engine= create_engine(DATABASE_URL)

sessionLocal= sessionmaker(autoflush=False, autocommit=False, bind=engine)

Base = declarative_base()

questions_list = [
    "What are the three fundamental pillars of all IT support?",
    "Why is it crucial never to make assumptions about a user's knowledge?",
    "What is the first question to ask when a new problem arises?",
    "Why is it said that a computer kept in its box never develops a problem?",
    "How does changing hardware like a printer affect technical support?",
    "What role does the human factor play in the occurrence of IT failures?",
    "Why is the language barrier a major challenge for support?",
    "What is the definition of the term numpty in the context of IT support?",
    "What is the difference between first-line support and third-line support?",
    "How does the interconnectivity of modern systems complicate technical diagnosis?",
    "Why must a technician remain professional when faced with simple user errors?",
    "What is the primary goal of preventive workstation configuration?",
    "How can a system update simultaneously impact an entire office?",
    "Why is it crucial to determine the exact time a problem started?",
    "What is IT aptitude and how is it acquired over time?",
    "What impact do unofficial system modifications have on stability?",
    "Why is the experience of fixing one's own mistakes formative for a technician?",
    "What is the importance of the Asset Tag during troubleshooting?",
    "How to manage a user who watches your technical intervention too closely?",
    "Why is it dangerous to clean a laptop keyboard with water?",
    "Why should a technician never openly mock a client?",
    "How to check if a problem comes from the power supply or the hardware?",
    "What is the advantage of knowing a device's maintenance history?",
    "How can a single letter in a model number change the support process?",
    "Why do servers sometimes have multiple input devices connected by mistake?",
    "Why should you avoid using technical jargon with end users?",
    "How to adapt your technical language level according to the user profile?",
    "Why prefer closed questions during the initial phase of a diagnosis?",
    "What does it mean to take the user on the troubleshooting journey?",
    "Why is it useful to ask the user to repeat your instructions?",
    "What is the effect of giving too many technical instructions at once to a novice?",
    "How does a non-technical dictionary help in communicating with users?",
    "What does an average user usually mean when pointing to their computer?",
    "Why might a user confuse an Android tablet with an Apple product?",
    "How to identify a device brand without asking a direct technical question?",
    "What are the specific challenges related to online chat technical support?",
    "Why is the user's response speed important in messaging support?",
    "How does the stress of an imminent deadline affect user communication?",
    "Why might a user fail to mention a crucial piece of technical information?",
    "How to turn a user into a valuable ally for the IT department?",
    "Why is it important to treat every user as a unique individual?",
    "What is the impact of self-esteem on an employee's learning ability?",
    "How to react to the frustration of a user whose expensive device is broken?",
    "Why must support be patient with smartphone users?",
    "How to ask to check cables without giving the impression of doubting the user?",
    "What is the best method for having a complex command entered remotely?",
    "Why are users who try to fix things themselves a challenge?",
    "How to handle an employee's lack of interest during a mandatory training session?",
    "What is the advantage of using metaphors like Sherlock Holmes?",
    "Why should you never patronize a struggling user's intelligence?",
    "What is the process of elimination applied to IT troubleshooting?",
    "Why is it advised to start at the end without working backwards?",
    "How does the use of flow logic simplify complex interventions?",
    "Why is it risky to rely solely on assumptions without a method?",
    "How to isolate an email synchronization problem using a browser?",
    "What action allows the user's hardware to be ruled out as the cause of an error?",
    "Why does a methodical approach prevent poor quality repairs?",
    "What does the phrase joining the dots mean during a root cause search?",
    "What questions should be asked to reconstruct the user's actions before a crash?",
    "How does removing a parent component affect the analysis of sub-elements?",
    "Why is keeping an open mind a vital quality for a support technician?",
    "What is the first hardware reflex to test systematically during a failure?",
    "How to distinguish official software from an illegally installed program?",
    "Why do developer profiles pose particular challenges for support?",
    "What is the interest of the KISS simplicity rule in the technical field?",
    "Why must every support request end with a formal resolution?",
    "How does rigorous ticket tracking facilitate service billing?",
    "Why is it important to precisely document the closing of a case?",
    "How to build an effective directory of the most common problems and solutions?",
    "What is the supervisor's role in validating support interventions?",
    "How can analyzing unusual solutions reduce future costs?",
    "Why structure troubleshooting guides as logical flowcharts?",
    "How to ensure service continuity in the event of a technician's absence?",
    "Why is active collaboration within the technical team essential?",
    "What to do if a higher-level technician does not have the expertise for a specific case?",
    "How to effectively transfer an ongoing case to a new colleague?",
    "Why are clarity and conciseness the keys to good documentation?",
    "What is the real advantage of an Asset Tag search system in a company?",
    "How can a standardized procedure avoid significant financial losses?",
    "Why are users said to be the technician's eyes and ears?",
    "What are the main types of standard interfaces encountered in the field?",
    "What are the security risks associated with using old versions of Windows?",
    "How do major Windows 10 updates impact daily support?",
    "What is the average software support lifespan for mobile systems?",
    "How do temperature and humidity conditions affect servers?",
    "What is the real impact of dust on the longevity of electronic components?",
    "How do weather factors influence the stability of wireless connections?",
    "Why is Wi-Fi signal sometimes unstable depending on a building's structure?",
    "What are the physical limits of Bluetooth and cellular technologies in the city?",
    "Why do hardware components inevitably end up wearing out?",
    "What is the utility of a UPS for protecting a computer's data?",
    "How to integrate old peripherals on modern operating systems?",
    "What are the classic symptoms of a device driver conflict?",
    "How does Windows ensure compatibility with old communication ports?",
    "What challenges do wearable connected objects pose for corporate support?",
    "What is the impact of accessibility needs on equipment choices?",
    "How can a user's personal settings destabilize a system?",
    "Why is computer hardware sometimes more predictable than the user?",
    "How does the legacy of Unix influence the structure of current systems?",
    "What is the importance of stable electrical voltage for PC health?",
    "How to diagnose a hardware problem via the device manager?",
    "Why does lightning represent a critical threat to network infrastructures?",
    "What is the role of USB standards in hardware interoperability?",
    "How do modern printer drivers facilitate their maintenance?",
    "Why do users often confuse the monitor with the central unit?",
    "Why does quality documentation save time and money?",
    "How to use Windows reliability history for a retrospective diagnosis?",
    "What is the primary function of the Event Viewer in Windows?",
    "How to interpret the different severity levels of Windows events?",
    "Why is it useful to create custom views in system logs?",
    "How to automate an action in response to a specific Windows event?",
    "What is the contribution of the task manager for quick resource analysis?",
    "How to extract detailed information with the system information utility?",
    "Why are text-format log files so valuable for support?",
    "What is a memory dump file and what is it used for after a crash?",
    "How to view the event logs of a remote machine on the network?",
    "Why is conciseness preferable to length in a technical report?",
    "How to structure forms for first-level support?",
    "What is the interest of adding free note sections in reports?",
    "Why avoid overly vague terms in technical documentation?",
    "How does automatic reporting help with predictive maintenance?",
    "Why is it necessary to record the caller's identity for every ticket?",
    "How to identify recurring problems using database data?",
    "What is the direct link between reporting and compliance with service contracts?",
    "Why is documentation the basis for technician training?",
    "How to simplify complex documentation so it is understood by all?",
    "What are the dangers of poor documentation during a team transition?",
    "Why is terminological consistency between technicians mandatory?",
    "How does the performance monitor allow for detecting slowdowns?",
    "What is the utility of administrative tools integrated into Windows?",
    "What are the major differences between Remote Desktop and Remote Assistance?",
    "How did the author s early experience as a tinkerer lead to his career in IT support?"
    "Why is the Quick Assist tool preferred for support to individuals?",
    "What are the most common third-party solutions for remote control?",
    "How to authorize remote administration via group policies?",
    "Why are remote administration functions often inactive by default?",
    "How to access and modify the registry of a remote computer on a domain?",
    "What is the use of the Microsoft Management Console for remote maintenance?",
    "What is the steps recorder and how does it help reproduce a bug?",
    "How can a simple screenshot speed up ticket resolution?",
    "What keyboard shortcut saves an image of the screen in Windows?",
    "Why is the Xbox Game Bar useful for documenting visual problems?",
    "What strategy to adopt when remote control is technically impossible?",
    "What is the advantage of screen sharing for end-user education?",
    "Why is it preferable to see the user performing their usual actions?",
    "How do browser-based tools facilitate multi-platform support?",
    "What are the cybersecurity risks associated with remote control software?",
    "How to check if a remote session is active on a workstation?",
    "Why is a stable connection required for interactive remote support?",
    "How to encourage user autonomy through visual guides?",
    "What is the impact of network latency on the smoothness of remote control tools?"
]