apiVersion: v1
kind: Service
metadata:
  name: backend-chatbot-service
spec:
  selector:
    app: chatbot  # This connects the service to your Deployment's Pods
  ports:
    - protocol: TCP
      port: 80         # Port exposed by the service
      targetPort: 8000  # Port your FastAPI app is listening on
  type: NodePort      # Use NodePort so you can access it easily in Minikube